"""empty message

Revision ID: ca6dedf3b472
Revises: 3dbf671359eb
Create Date: 2022-07-30 14:09:19.323938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca6dedf3b472'
down_revision = '3dbf671359eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('name', sa.String(length=80), nullable=False))
    op.drop_column('file', 'file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('file', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('file', 'name')
    # ### end Alembic commands ###
