"""empty message

Revision ID: e2124d38bde4
Revises: 48b521375e4a
Create Date: 2023-11-04 10:29:16.269680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2124d38bde4'
down_revision = '48b521375e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'canModify', nullable=False, new_column_name='followed')
    op.add_column('permissions', sa.Column('canInvite', sa.Boolean(), nullable=False, server_default='False'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'followed', nullable=False, new_column_name='canModify')
    op.drop_column('permissions', 'canInvite')
    # ### end Alembic commands ###
